### PR TITLE
fix(discord.js-utilities): message prompter confirm strategy

### PR DESCRIPTION
**Pull request by jurienhamaker**

### CODE REVIEW

**Review by Favna — APPROVED** [review]

**Review by kyranet — APPROVED** [review]

**Comment by Favna** [comment]
@all-contributors please add @jurienhamaker for code

**Comment by jurienhamaker** [comment]
@Favna doesn't seem to work on merged pr's

**Comment by vladfrangu** [comment]
> @Favna doesn't seem to work on merged pr's

You were saying?

**Comment by kyranet** [comment]
> > @Favna doesn't seem to work on merged pr's
> 
> You were saying?

It spammed `#github-all` tho

**Pull request merged**
